// Error code constants organized by category
// See docs/error-codes.md for full documentation

export const ErrorCodes = {
  // Authentication (401)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_PROVIDER_UNAVAILABLE: 'AUTH_PROVIDER_UNAVAILABLE',
  AUTH_OAUTH_STATE_INVALID: 'AUTH_OAUTH_STATE_INVALID',

  // Authorization (403)
  AUTHZ_INSUFFICIENT_ROLE: 'AUTHZ_INSUFFICIENT_ROLE',
  AUTHZ_INSUFFICIENT_PERMISSIONS: 'AUTHZ_INSUFFICIENT_PERMISSIONS',
  AUTHZ_TENANT_ACCESS_DENIED: 'AUTHZ_TENANT_ACCESS_DENIED',
  AUTHZ_RESOURCE_ACCESS_DENIED: 'AUTHZ_RESOURCE_ACCESS_DENIED',

  // Validation (400)
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_FIELD_REQUIRED: 'VALIDATION_FIELD_REQUIRED',
  VALIDATION_FIELD_INVALID: 'VALIDATION_FIELD_INVALID',
  VALIDATION_BODY_MALFORMED: 'VALIDATION_BODY_MALFORMED',

  // Tenant (400/404/409)
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SLUG_TAKEN: 'TENANT_SLUG_TAKEN',
  TENANT_DISABLED: 'TENANT_DISABLED',
  TENANT_MEMBER_EXISTS: 'TENANT_MEMBER_EXISTS',
  TENANT_MEMBER_NOT_FOUND: 'TENANT_MEMBER_NOT_FOUND',
  TENANT_INVITE_CODE_INVALID: 'TENANT_INVITE_CODE_INVALID',
  TENANT_INVITE_CODE_EXPIRED: 'TENANT_INVITE_CODE_EXPIRED',
  TENANT_JOIN_REQUEST_EXISTS: 'TENANT_JOIN_REQUEST_EXISTS',
  TENANT_JOIN_REQUEST_NOT_FOUND: 'TENANT_JOIN_REQUEST_NOT_FOUND',
  TENANT_USER_LIMIT_REACHED: 'TENANT_USER_LIMIT_REACHED',

  // Workflow (400/404/409)
  WF_NOT_FOUND: 'WF_NOT_FOUND',
  WF_DUPLICATE_NAME: 'WF_DUPLICATE_NAME',
  WF_NOT_DRAFT: 'WF_NOT_DRAFT',
  WF_NOT_PUBLISHED: 'WF_NOT_PUBLISHED',
  WF_INVALID_BPMN: 'WF_INVALID_BPMN',
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  WORKFLOW_INVALID_STATUS_TRANSITION: 'WORKFLOW_INVALID_STATUS_TRANSITION',
  WORKFLOW_PUBLISH_VALIDATION_FAILED: 'WORKFLOW_PUBLISH_VALIDATION_FAILED',
  WORKFLOW_VERSION_CONFLICT: 'WORKFLOW_VERSION_CONFLICT',
  WORKFLOW_DELETE_NOT_DRAFT: 'WORKFLOW_DELETE_NOT_DRAFT',

  // Instance (400/404)
  INSTANCE_NOT_FOUND: 'INSTANCE_NOT_FOUND',
  INSTANCE_INVALID_STATE: 'INSTANCE_INVALID_STATE',
  INSTANCE_ALREADY_COMPLETED: 'INSTANCE_ALREADY_COMPLETED',
  INSTANCE_ALREADY_CANCELLED: 'INSTANCE_ALREADY_CANCELLED',
  INSTANCE_NOT_RUNNING: 'INSTANCE_NOT_RUNNING',

  // Task (400/404/409)
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_INVALID_STATE: 'TASK_INVALID_STATE',
  TASK_ALREADY_CLAIMED: 'TASK_ALREADY_CLAIMED',
  TASK_ALREADY_COMPLETED: 'TASK_ALREADY_COMPLETED',
  TASK_NOT_ASSIGNED: 'TASK_NOT_ASSIGNED',
  TASK_NOT_CLAIMABLE: 'TASK_NOT_CLAIMABLE',
  TASK_FORM_VALIDATION_FAILED: 'TASK_FORM_VALIDATION_FAILED',

  // Expression (400)
  EXPRESSION_SYNTAX_ERROR: 'EXPRESSION_SYNTAX_ERROR',
  EXPRESSION_EVALUATION_FAILED: 'EXPRESSION_EVALUATION_FAILED',
  EXPRESSION_TIMEOUT: 'EXPRESSION_TIMEOUT',
  EXPRESSION_MEMORY_EXCEEDED: 'EXPRESSION_MEMORY_EXCEEDED',

  // Integration (502/504)
  INTEGRATION_CONNECTION_FAILED: 'INTEGRATION_CONNECTION_FAILED',
  INTEGRATION_TIMEOUT: 'INTEGRATION_TIMEOUT',
  INTEGRATION_SSRF_BLOCKED: 'INTEGRATION_SSRF_BLOCKED',
  INTEGRATION_CIRCUIT_BREAKER_OPEN: 'INTEGRATION_CIRCUIT_BREAKER_OPEN',

  // Rate Limiting (429)
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // SLA (400/404/409)
  SLA_NOT_FOUND: 'SLA_NOT_FOUND',
  SLA_ALREADY_ACKNOWLEDGED: 'SLA_ALREADY_ACKNOWLEDGED',

  // Concurrency (409)
  CONCURRENCY_LOCK_FAILED: 'CONCURRENCY_LOCK_FAILED',
  CONCURRENCY_VERSION_CONFLICT: 'CONCURRENCY_VERSION_CONFLICT',

  // Internal (500)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INTERNAL_DATABASE_ERROR: 'INTERNAL_DATABASE_ERROR',
  INTERNAL_REDIS_ERROR: 'INTERNAL_REDIS_ERROR',
  INTERNAL_QUEUE_ERROR: 'INTERNAL_QUEUE_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
